### ISSUE TITLE
Why does ths app require localization?

### ISSUE THREAD

**Issue by svein83** [yolosec/routerkeygenAndroid#7]
I was testing your app, and it asked for localization. AFAIK There is no reason for this. I found no explanation or clarification in the readme or the docs. So i just declined and uninstalled.

**Comment by ph4r05** [comment]
The application itself clarifies why the localization is needed. Also the google play info clearly states that:
"UPDATE: Location privilege is required by Android 6+ in order to allow app scan for WiFis.
The reason is the WiFi scan leaks user location (by WiFi MAC maps) so Android won't allow Routerkeygen Yolosec to scan WiFis without you granting location privilege for the app.

Please note we don't use your GPS (feel free to verify that in our source codes) nor send any data anywhere. The application is also Add free!"


https://stackoverflow.com/questions/36344239/performing-network-scan-requiring-permission-for-coarse-location

**Comment by svein83** [comment]
I got it from F-Droid No info about it there
![20180519_130657](https://user-images.githubusercontent.com/25469452/40268004-0aaffa4a-5b66-11e8-84a0-c416435bbbed.jpg)

And no info in the app
![screenshot_20180519-130019](https://user-images.githubusercontent.com/25469452/40268016-44086c64-5b66-11e8-8533-c493671742d5.png)
![screenshot_20180519-130032](https://user-images.githubusercontent.com/25469452/40268018-50006422-5b66-11e8-9091-9ce3ab9f8cbc.jpg)
